複数リポジトリでプルリク情報にデータが入らない問題の解消
cosoji-jp/github-gas-four-keys pull request #3
Opened 2024-06-17 10:48 UTC by 9wick

複数リポジトリを設定した際に、取得がうまく行かない問題がありましたので、修正のpull-reqestさせていただきます。
よろしくお願いいたします。

## 問題
複数リポジトリで設定した際に、pull-reqestが「プルリク情報」シートに記入されないものがある。

## 対応
pull-requestを記入するシートの行のカウントとpull-requestのindexが連動してしまい不整合を起こしていたので
その部分を修正。

2024-07-02 21:15 UTC, ukiuki-satoshi requested changes
PRありがとうございます！
バグ内容確認致しました。
1点コメント致しましたのでご確認頂ければと存じます。

2024-07-02 21:15 UTC, ukiuki-satoshi commented on main.js
> +    for (const pullRequest of pullRequests.length) {
```js
for (const pullRequest of pullRequests) {
```
こちら正しくは👆ではないでしょうか？

PRのコードを実行したところ👇のエラーが出ております。
![スクリーンショット 2024-07-03 6 10 30](https://github.com/cosoji-jp/github-gas-four-keys/assets/39693776/b9be52de-c483-4d92-96f5-0a690bcd2385)

参考資料: [for...ofのMSDNリファレンス](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/for...of)

2024-07-02 21:47 UTC, ukiuki-satoshi requested changes

2024-07-02 21:47 UTC, ukiuki-satoshi commented on main.js
> +    for (const pullRequest of pullRequests.length) {
```suggestion
    for (const pullRequest of pullRequests) {
```
こちら正しくは👆ではないでしょうか？

PR頂いたコードを実行したところ👇のエラーが出ております。
![スクリーンショット 2024-07-03 6 10 30](https://github.com/cosoji-jp/github-gas-four-keys/assets/39693776/b9be52de-c483-4d92-96f5-0a690bcd2385)

参考資料: [for...ofのMSDNリファレンス](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/for...of)

2024-07-14 00:35 UTC, ukiuki-satoshi approved these changes
こちらマージさせて頂きます！

2024-07-14 00:45 UTC, merged

2024-07-17 15:02 UTC, 9wick commented on main.js
> +    for (const pullRequest of pullRequests.length) {
通知に気づかず失礼いたしました🙇‍♂️
修正ありがとうございます